version: "3.7"
services:
  test_machine:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.test_machine.tls.certresolver=myresolver
      - traefik.http.routers.test_machine.rule=Host(`test.$DOMAIN`) || Host(`test2.$DOMAIN`) || Host(`test3.$DOMAIN`)
    networks:
      - frontend

networks:
  frontend:
    external: true


