
version: "3.7"
services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt
      - traefik.http.routers.whoami.tls.domains[0].main=betabillet.tech
      - traefik.http.routers.whoami.tls.domains[0].sans=*.betabillet.tech

      - traefik.http.routers.whoami.rule=Host(`proutprout.betabillet.tech`)
      - traefik.http.routers.whoami.entrypoints=websecure

    networks:
      - frontend

networks:
  frontend:
    external: true

