
version: "3.7"
services:
  test_machine:
    image: python:3.7-slim
    ports:
      - 8884:8884
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.website.rule=Host(`nick.maietta.org`)

    networks:
      - frontend
    command: "python3 -m http.server 8884"

networks:
  frontend:
    external: true

