
version: "3.7"
services:
  test_machine:
    image: python:3.7-slim
    ports:
      - 8884:8884
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend

      - traefik.http.routers.test_machine.rule=Host(`test.tibillet.org`)
      - traefik.http.routers.test_machine.entrypoints=websecure

      - traefik.http.routers.test_machine.tls.certresolver=myresolver
      - traefik.http.services.test_machine.loadbalancer.server.port=8884

    networks:
      - frontend
    command: "python3 -m http.server 8884"
