
version: "3.7"
services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.tibillet.org`)"
      - "traefik.http.routers.wp01.rule=HostRegexp(`{sub:[a-zA-Z0-9-]+}.tibillet.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

    networks:
      - frontend

networks:
  frontend:
    external: true

